kind: pipeline
name: docker

trigger:
  branch:
    - dev

platform:
  runner: 10.11.92.40

workspace:
  path: github.com/drone-runners/drone-runner-docker

volumes:
  - name: go
    host:
      path: /data/cache/golang/pkg
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: golang
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.17.3-bullseye
    volumes:
      - name: go
        path: /go/pkg
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - git apply .beagle/0001-lables.patch
      - git apply .beagle/0002-disable-create-network.patch
      - git apply .beagle/0003-ci-workspace.patch
      - sh .beagle/build.sh

  - name: tmate-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate:2.4.0-amd64
    commands:
      - cp /build/tmate release/linux/amd64/tmate

  - name: tmate-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate:2.4.0-arm64
    commands:
      - cp /build/tmate release/linux/arm64/tmate

  - name: tmate-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate:2.4.0-ppc64le
    commands:
      - cp /build/tmate release/linux/ppc64le/tmate

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:bullseye-slim-amd64
      dockerfile: .beagle/dockerfile
      repo: wod/drone-runner-docker
      version: v1.6.3
      channel: alpha-amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:bullseye-slim-arm64
      dockerfile: .beagle/dockerfile
      repo: wod/drone-runner-docker
      version: v1.6.3
      channel: alpha-arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:bullseye-slim-ppc64le
      dockerfile: .beagle/dockerfile
      repo: wod/drone-runner-docker
      version: v1.6.3
      channel: alpha-ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  # - name: docker-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
  #   volumes:
  #     - name: docker
  #       path: /var/run/docker.sock
  #   settings:
  #     base: registry.cn-qingdao.aliyuncs.com/wod/debian:bullseye-slim-mips64le
  #     dockerfile: .beagle/dockerfile
  #     repo: wod/drone-runner-docker
  #     version: v1.6.3
  #     channel: alpha-mips64le
  #     args: 'TARGETOS=linux,TARGETARCH=mips64le'
  #     registry: registry.cn-qingdao.aliyuncs.com
  #     registry_user:
  #       from_secret: REGISTRY_USER_ALIYUN
  #     registry_password:
  #       from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      template: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-alpha-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor

trigger:
  branch:
    - master

platform:
  runner: 10.11.92.40

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: harbor-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-alpha-amd64
      target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-amd64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    when:
      branch:
        - master

  - name: harbor-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-alpha-arm64
      target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-arm64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-alpha-ppc64le
      target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-ppc64le
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  # - name: harbor-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
  #   volumes:
  #     - name: docker
  #       path: /var/run/docker.sock
  #   settings:
  #     source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-alpha-mips64le
  #     target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-mips64le
  #     registry: registry.cn-qingdao.aliyuncs.com
  #     registry_user:
  #       from_secret: REGISTRY_USER_ALIYUN
  #     registry_password:
  #       from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      template: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - harbor-amd64
      - harbor-arm64
      - harbor-ppc64le

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: USERNAME
  path: devops-registry-aliyun

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: PASSWORD
  path: devops-registry-aliyun
