kind: pipeline
name: docker

trigger:
  branch:
    - dev

platform:
  runner: 10.11.92.40

workspace:
  path: /go/src/github.com/drone-runners/drone-runner-docker

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0

  - name: s3-cache
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./vendor
      endpoint: https://cache.wodcloud.com
      access_key:
        from_secret: ACCESS_KEY_MINIO
      secret_key:
        from_secret: SECRET_KEY_MINIO

  - name: golang
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.19
    commands:
      - git apply .beagle/0001-lables.patch
      - git apply .beagle/0002-disable-create-network.patch
      - git apply .beagle/0003-ci-workspace.patch
      - sh .beagle/build.sh

  - name: tmate-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate:2.4.0-amd64
    commands:
      - cp /bin/tmate release/linux/amd64/tmate

  - name: tmate-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate:2.4.0-arm64
    commands:
      - cp /bin/tmate release/linux/arm64/tmate

  - name: tmate-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate:2.4.0-ppc64le
    commands:
      - cp /bin/tmate release/linux/ppc64le/tmate

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:bullseye-slim-amd64
      dockerfile: .beagle/dockerfile
      repo: wod/drone-runner-docker
      version: v1.8.0
      channel: alpha-amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:bullseye-slim-arm64
      dockerfile: .beagle/dockerfile
      repo: wod/drone-runner-docker
      version: v1.8.0
      channel: alpha-arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:bullseye-slim-ppc64le
      dockerfile: .beagle/dockerfile
      repo: wod/drone-runner-docker
      version: v1.8.0
      channel: alpha-ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  # - name: docker-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
  #   volumes:
  #     - name: docker
  #       path: /var/run/docker.sock
  #   settings:
  #     base: registry.cn-qingdao.aliyuncs.com/wod/debian:bullseye-slim-mips64le
  #     dockerfile: .beagle/dockerfile
  #     repo: wod/drone-runner-docker
  #     version: v1.8.0
  #     channel: alpha-mips64le
  #     args: 'TARGETOS=linux,TARGETARCH=mips64le'
  #     registry: registry.cn-qingdao.aliyuncs.com
  #     registry_user:
  #       from_secret: REGISTRY_USER_ALIYUN
  #     registry_password:
  #       from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      template: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-alpha-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-alpha
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor

trigger:
  branch:
    - master

platform:
  runner: 10.11.92.40

clone:
  disable: true

steps:
  - name: harbor-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-alpha-amd64
      target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-amd64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    when:
      branch:
        - master

  - name: harbor-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-alpha-arm64
      target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-arm64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-alpha-ppc64le
      target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-ppc64le
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  # - name: harbor-mips64le
  #   image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
  #   settings:
  #     source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-alpha-mips64le
  #     target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-mips64le
  #     registry: registry.cn-qingdao.aliyuncs.com
  #     registry_user:
  #       from_secret: REGISTRY_USER_ALIYUN
  #     registry_password:
  #       from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      template: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.8.0
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: USERNAME
  path: devops-registry-aliyun

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: PASSWORD
  path: devops-registry-aliyun

---
kind: secret
name: ACCESS_KEY_MINIO
get:
  name: ACCESS_KEY
  path: devops-minio

---
kind: secret
name: SECRET_KEY_MINIO
get:
  name: SECRET_KEY
  path: devops-minio
