platform: 10.11.92.33

workspace:
  base: /go
  path: src/github.com/drone/drone

clone:
  git:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    dns: 223.5.5.5
    when:
      branch:
        - dev

pipeline:
  golang:
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.16.5-alpine
    dns: 223.5.5.5
    volumes:
      - /data/cache/golang/mod:/go/pkg/mod
    environment:
      - GOPROXY=https://goproxy.cn
    commands:
      - git apply .beagle/0001-lables.patch
      - sh .beagle/build.sh
    when:
      branch:
        - dev

  tmate-amd64:
    image: registry.cn-qingdao.aliyuncs.com/wod-k8s/tmate:v2.4.0-amd64
    dns: 223.5.5.5
    commands:
      - cp /build/tmate release/linux/amd64/tmate
    when:
      branch:
        - dev

  tmate-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod-k8s/tmate:v2.4.0-arm64
    dns: 223.5.5.5
    commands:
      - cp /build/tmate release/linux/arm64/tmate
    when:
      branch:
        - dev

  tmate-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod-k8s/tmate:v2.4.0-ppc64le
    dns: 223.5.5.5
    commands:
      - cp /build/tmate release/linux/ppc64le/tmate
    when:
      branch:
        - dev

  docker-amd64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.13
    dockerfile: .beagle/dockerfile
    repo: wod/drone-runner-docker
    version: v1.6.3
    channel: beta-amd64
    args: 'TARGETOS=linux,TARGETARCH=amd64'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - dev

  docker-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.13-arm64
    dockerfile: .beagle/dockerfile
    repo: wod/drone-runner-docker
    version: v1.6.3
    channel: beta-arm64
    args: 'TARGETOS=linux,TARGETARCH=arm64'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - dev

  docker-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.13-ppc64le
    dockerfile: .beagle/dockerfile
    repo: wod/drone-runner-docker
    version: v1.6.3
    channel: beta-ppc64le
    args: 'TARGETOS=linux,TARGETARCH=ppc64le'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - dev

  docker-arch:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    platforms: linux/amd64,linux/arm64,linux/ppc64le
    template: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-beta-ARCH
    target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-beta
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: DOCKER_USERNAME
      - source: REGISTRY_PASSWORD_ALIYUN
        target: DOCKER_PASSWORD
    when:
      branch:
        - dev

  harbor-amd64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-beta-amd64
    target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-amd64
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  harbor-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-beta-arm64
    target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-arm64
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  harbor-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-beta-ppc64le
    target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-ppc64le
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  docker-arch:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    platforms: linux/amd64,linux/arm64,linux/ppc64le
    template: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3-ARCH
    target: registry.cn-qingdao.aliyuncs.com/wod/drone-runner-docker:v1.6.3
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: DOCKER_USERNAME
      - source: REGISTRY_PASSWORD_ALIYUN
        target: DOCKER_PASSWORD
    when:
      branch:
        - master
